vm_id                = 900
vm_name              = "ubuntu-22-04-server-raw"
iso_file             = "ubuntu-22-04-server-raw.iso"
template_description = "Ubuntu server 22.04 template with the bare minimum configuration generated by Packer on {{ isotime `2006-01-02` }}."
