proxmox_url          = "https://pve-01.lan.homelab:8006/api2/json"
node                 = "pve-01"
vm_id                = 901
build_name           = "ubuntu"
vm_name              = "ubuntu-24-04-server-raw"
iso_file             = "ubuntu-24.04-live-server-amd64.iso"
template_description = "Ubuntu server 24.04 template with the bare minimum configuration generated by Packer on {{ isotime `2006-01-02` }}."
network_adapters = {
  "01" = {
    bridge   = "vmbr100"
    model    = "virtio"
    vlan_tag = ""
    firewall = false
  }
}
