---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - {name: "sudo"} # To enable elevated command.
      - {name: "qemu-guest-agent"} # To enhance Proxmox integration with the VM.
      - {name: "openssh-server"} # To enable SSH.
      - {name: "cloud-init"} # To enable cloud-init.
      - {name: "python-is-python3"}
      - {name: "pipx"} # A tool for installing and managing Python packages.
      - {name: "python3-passlib"} # Required to use bcrypt.
      - {name: "python3-jmespath"} # Required to use bcrypt.
      - {name: "ubuntu-drivers-common"} # To enable the installation of the latest drivers.
  notify: "Refresh ~/.bashrc"

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: "flush_handlers"
